name = "STM32 C"
grammar = "c"
path_suffixes = ["c", "h"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
]
autoclose_before = ";:.,=}])> \n\t"
